config/routes.rb
Rails.application.routes.draw do
  get 'interactive/page'
  get 'interactive/hebele'
  get 'interactive/deneme'

  resources :searches
  get 'search', to: "searches#index"
  get 'shows', to: "searches#show"
  post 'shows', to: "searches#show"

  get 'searches/search'
  root 'quakes#index'
  get 'quakes/:id', to: "quakes#show"
  get 'quakes', to: "quakes#index"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/distance.rb
class Distance < ApplicationRecord
    class <<self
      def search(city_name,maximum_distance,minimum_distance)
    #  quake=Quake.all
      dep=Distance.all
      @city_name_graph=dep.where(["city LIKE ?","%#{city_name}%"])
      dep=dep.where(["city LIKE ?","%#{city_name}%"])
      dep=dep.where(["distance <= ?",maximum_distance])
      dep=dep.where(["distance >= ?",minimum_distance])
      return dep
      end

      def search2(place)
    #  quake=Quake.all
      dep=Quake.all
      dep=dep.where(["place LIKE ?","%#{place}%"])
      return dep
      end
    end
end

app/models/quake.rb
class Quake < ApplicationRecord
require 'terminal-notifier'
require 'date'
gem "mysql2"
@x=" "
client = Mysql2::Client.new(:host=>"localhost",:username=>"root",:password=>"abcde",:database=>"watchers_of_quakes_development")

  class <<self
    def search(city_name)
  #  quake=Quake.all
    dep=Distance.all
    dep=dep.where(["city LIKE ?","%#{city_name}%"]) if city_name.present?

    return dep
    end
  end

  def asdfinder
    g = GeoIP.new File.join(Rails.root, "db", "GeoLiteCity.dat")
    geodata = g.city("94.55.235.31")
    city=geodata[7]
    i=0
    @quakes=Quake.all
    @quakes.each do |quake|
      if i<=10
        if city.match(quake.city.to_s)&&Date.today.to_s.include?(quake.date.to_s)
          TerminalNotifier.notify(" #{quake.siddet} buyuklugunde Deprem OLDU! ", :title => 'WATCHERS OF QUAKES',
                                                :subtitle => " DEPREM #{quake.place}")

                                                i+=1

      else

      end
    end
  end
    if i==0
      TerminalNotifier.notify(" BUGÜN #{city}'de DEPREM YOK ", :title => 'WATCHERS OF QUAKES')
    end
end#endof asdfinder

end

app/models/sehir.rb
class Sehir < ApplicationRecord
class <<self
  def date_detector
    require 'mysql2'
    city_name="Adana"
    file=open("/Users/emirozbir/Desktop/ruby/watchers_of_quakes/app/views/Adana.csv","a")
    file.puts("date,count")
    data=client.query("SELECT * FROM cities WHERE city_name LIKE '%#{city_name}%'")
    month=["November","December"]
    month.each do |month|
        data.each do |meta_data_city|
          file.puts month.to_s+","+meta_data_city["#{month.downcase}"].to_s
        end
      end
    return city_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/interactive_controller.rb
class InteractiveController < ApplicationController
require 'mysql2'

  def page
    @quakes = Quake.all
    @hash = Gmaps4rails.build_markers(@quakes) do |quake, marker|
      marker.lat quake.latitude
      marker.lng quake.longitude
      marker.infowindow quake.place
    end
    @info_date=Quake.last
    @info_date2=Quake.first
    @quakes2 = Quake.limit(10)
    @cities=Distance.uniq.pluck(:city)

  end
  def hebele
    @like_keyword=Distance.search2(params[:place]).all
    @label=@like_keyword.first

  #  @qk=Quake.where("place LIKE ?", @like_keyword)
    ##call methods from Sehirs methods.
  #  @x=Sehir.date_detector
  end
end

app/controllers/quakes_controller.rb
class QuakesController < ApplicationController

def index
    @x=Quake.all
    @quakes = Quake.all

    @t=Quake.new
    @t.asdfinder
    

end
def show
    @dep=Quake.find(params[:id])
end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    #@cities=Sehir.uniq.pluck(:sehir_isim)
    @cities=Distance.uniq.pluck(:city)
    @artist_data=Quake.last
    @artist_data2=Quake.first
    @deneme=Distance.last
  end
  def search

  end

  def show
    @search=Distance.search(params[:city_name],params[:maximum_distance],params[:minimum_distance]).all

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interactive_helper.rb
module InteractiveHelper
end

app/helpers/quakes_helper.rb
module QuakesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/interactive/deneme.html.erb
<style>
#noty-holder{
  width: 100%;
  top: 0;
  font-weight: bold;
  z-index: 1031; /* Max Z-Index in Fixed Nav Menu is 1030*/
  text-align: center;
  position: fixed;
}

.alert{
  margin-bottom: 2px;
  border-radius: 0px;
}

#main{
  min-height:900px;
}

body {
padding-top: 50px;
}
.starter-template {
padding: 40px 15px;
text-align: center;
}
</style>

<script>
function createNoty(message, type) {
    var html = '<div class="alert alert-' + type + ' alert-dismissable page-alert">';
    html += '<button type="button" class="close"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>';
    html += message;
    html += '</div>';
    $(html).hide().prependTo('#noty-holder').slideDown();
};

$(function(){
    createNoty('success', 'success');
    $('.page-alert .close').click(function(e) {
        e.preventDefault();
        $(this).closest('.page-alert').slideUp();
    });
});
</script>
<div id="noty-holder"></div><!-- HERE IS WHERE THE NOTY WILL APPEAR-->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          </button>
        </div>

      </div>
    </nav>

app/views/interactive/hebele.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
body{ margin-top:20px;}
.glyphicon { margin-right:5px;}
.rating .glyphicon {font-size: 10px;}
.rating-num { margin-top:0px;font-size: 44px; }
.progress { margin-bottom: 5px;}
.progress-bar { text-align: left; }
.rating-desc .col-md-3 {padding-right: 0px;}
.sr-only { margin-left: 5px;overflow: visible;clip: auto; }
.container{
  margin-left: 0em;

}
.graph1{

}
.graph2{
    margin-left: 50em;
    margin-top: -35em;
    margin-right: 12em;

}
#container2{
  margin-left: 40em;
  margin-top: -14em;
}
</style>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>


<%i=0%>

<%i2=0%>
<%i3=0%>
<%i4=0%>
<%i5=0%>

<%@like_keyword.each do |x|%>
  <%i+=1%>
  <%if x.siddet>=5%>
    <%i5+=1%>
  <%end%>
  <%if x.siddet<=4&&x.siddet>3.1%>
    <%i4+=1%>
  <%end%>

  <%if x.siddet<=3&&x.siddet>2.1%>
    <%i3+=1%>
  <%end%>
  <%if x.siddet<=2&&x.siddet>1.0%>
    <%i2+=1%>
  <%end%>
<%end%>
<%datas=[]%>
<%t=0%>
<%@like_keyword.each do |data|%>
  <%datas.push(data.siddet)%>
  <%t+=1%>
<%end%>

<div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-xs-12 col-md-6 text-center">
                      <h1 class="rating-num"><%=@label.city%></h1>
                        <h1 class="rating-num">
                            <%="#{i}"%><h1>
                        <div class="rating">
                            <span class="glyphicon glyphicon"></span><span class="glyphicon glyphicon">
                            </span><span class="glyphicon glyphicon"></span><span class="glyphicon glyphicon">
                            </span><span class="glyphicon glyphicon"></span>
                        </div>
                    </div>
                    <div class="col-xs-10 col-md-6">
                        <div class="row rating-desc">
                            <div class="col-xs-3 col-md-3 text-right">
                                <span class="glyphicon glyphicon"></span>5
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress progress-striped">
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width:<%=i5%>%;">
                                        <span class="sr-only"><%"#{i5}"%></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-3 col-md-3 text-right">
                                <span class="glyphicon glyphicon"></span>4
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width:<%=i4*10%>%">
                                        <span class="sr-only"><%=i4%></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-3 col-md-3 text-right">
                                <span class="glyphicon glyphicon"></span>3
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width:<%= i3*10 %>%">
                                        <span class="sr-only"><%=i3%></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-3 col-md-3 text-right">
                                <span class="glyphicon glyphicon"></span>1 - 2
                            </div>
                            <div class="col-xs-8 col-md-9">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20"
                                        aria-valuemin="0" aria-valuemax="100" style="width: <%= i2*10 %>%">
                                        <span class="sr-only"><%="#{i2}"%></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container" id="container2">
    <br>
	<div class="well">

        <p>
            <H3 ><%="EN YÜKSEK DEPREM BÜYÜKLÜĞÜ #{datas.max} "%><H3>
        </p>
	</div>
</div>
</div>
<div class="graph1">
<%= line_chart @like_keyword.group_by_day(:date).count ,width: "600px", height: "500px" ,colors: ["#b00", "#666"],label: "Deprem Sayisi", xtitle: "Tarih",ytitle:"Deprem Sayısı",legend: "bottom"%>
</div>
<div class="graph2">
<%= area_chart @like_keyword.group_by_day(:date).maximum(:siddet),width: "720px", height: "500px" ,colors: ["#a11342", "white"],label: "Buyukluk", xtitle: "Tarih",ytitle:"Buyukluk",legend: "bottom" %>
</div>

app/views/interactive/page.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/css/bootstrap-select.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/bootstrap-select.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.1/js/i18n/defaults-*.min.js"></script>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

<html>

<head>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <style>
  body{ margin-top:20px;
    background-color:rgb(68, 179, 234);
  }
  .glyphicon { margin-right:5px;}
  .rating .glyphicon {font-size: 10px;}
  .rating-num { margin-top:0px;font-size: 44px; }
  .progress { margin-bottom: 5px;}
  .progress-bar { text-align: left; }
  .rating-desc .col-md-3 {padding-right: 0px;}
  .sr-only { margin-left: 5px;overflow: visible;clip: auto; }
  .container{
    margin-left: 0em;

  }
  .graph1{

  }
  .graph2{
      margin-left: 45em;
      margin-top: -35em;
      margin-right: 12em;

  }
  #container2{
    margin-left: 40em;
    margin-top: -24em;
    width: 585px;
  }
  .container{
    margin-left: 40em;
  }
  #divler{
    margin-left: 13em;
    margin-top: -5em;

  }
  </style>
<style>
  @import url("http://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.5.4/bootstrap-select.min.css");
  #selector{
  }
  body{
      background-repeat:no-repeat;
      background-size:cover;
    }
  #search-statistics{
    margin-left: 1em;
    margin-top: 2em;
  }
  #dep-label{
    color:white;
  }
  .graph2{
      margin-left: 50em;
      margin-top: -35em;
      margin-right: 12em;

  }
</style>
<head>
<body>
<div id="search-statistics">
  <h1 id="dep-label">DEPREM ANALİZLERİ</h1>


  <%= form_tag("http://localhost:3000/interactive/hebele", :method => "get", id: "search-form") do %>
      <div id="selector">
        <%= select_tag :place,options_for_select(@cities,id:"city_shower"),class:"selectpicker",:include_blank=>false%>
      </div>
      <br>
      <%= submit_tag "ARA",class:"btn3d btn btn-white btn-default" ,id:"submit"%>
      <%end%>

    </div>

    <br>
    <%i=0%>
    <%i2=0%>
    <%i3=0%>
    <%i4=0%>
    <%i5=0%>
    <%@quakes.each do |x|%>
      <%i+=1%>
      <%if x.siddet>=5%>
        <%i5+=1%>
      <%end%>
      <%if x.siddet<=4&&x.siddet>3.1%>
        <%i4+=1%>
      <%end%>

      <%if x.siddet<=3&&x.siddet>2.1%>
        <%i3+=1%>
      <%end%>
      <%if x.siddet<=2&&x.siddet>1.0%>
        <%i2+=1%>
      <%end%>
    <%end%>
    <%datas=[]%>
    <%t=0%>
    <%@quakes.each do |data|%>
      <%datas.push(data.siddet)%>
      <%t+=1%>
    <%end%>
<div id="divler">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-md-6">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-xs-12 col-md-6 text-center">
                          <h1 class="rating-num"><%="TÜRKİYE"%></h1>
                            <h1 class="rating-num">
                                <%="#{i}"%><h1>
                            <div class="rating">
                                <span class="glyphicon glyphicon"></span><span class="glyphicon glyphicon">
                                </span><span class="glyphicon glyphicon"></span><span class="glyphicon glyphicon">
                                </span><span class="glyphicon glyphicon"></span>
                            </div>
                        </div>
                        <div class="col-xs-10 col-md-6">
                            <div class="row rating-desc">
                                <div class="col-xs-3 col-md-3 text-right">
                                    <span class="glyphicon glyphicon"></span>5
                                </div>
                                <div class="col-xs-8 col-md-9">
                                    <div class="progress progress-striped">
                                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20"
                                            aria-valuemin="0" aria-valuemax="100" style="width:<%=i5%>%;">
                                            <span class="sr-only"><%"#{i5}"%></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-3 col-md-3 text-right">
                                    <span class="glyphicon glyphicon"></span>4
                                </div>
                                <div class="col-xs-8 col-md-9">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                                            aria-valuemin="0" aria-valuemax="100" style="width:<%=i4*10%>%">
                                            <span class="sr-only"><%=i4%></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-3 col-md-3 text-right">
                                    <span class="glyphicon glyphicon"></span>3
                                </div>
                                <div class="col-xs-8 col-md-9">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                                            aria-valuemin="0" aria-valuemax="100" style="width:<%= i3*10 %>%">
                                            <span class="sr-only"><%=i3%></span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-xs-3 col-md-3 text-right">
                                    <span class="glyphicon glyphicon"></span>1 - 2
                                </div>
                                <div class="col-xs-8 col-md-9">
                                    <div class="progress">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20"
                                            aria-valuemin="0" aria-valuemax="100" style="width: <%= i2*10 %>%">
                                            <span class="sr-only"><%="#{i2}"%></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container" id="container2">
        <br>
      <div class="well">

            <p>
                <H3 ><%="EN YÜKSEK DEPREM BÜYÜKLÜĞÜ #{datas.max} "%><H3>
            </p>
      </div>
    </div>
</div>
    <div class="graph1">
    <%= line_chart Quake.group_by_day(:date).count ,width: "600px", height: "500px" ,colors: ["#b00", "#666"],label: "Deprem Sayisi", xtitle: "Tarih",ytitle:"Deprem Sayısı",legend: "bottom"%>
    </div>
    <div class="graph2">
    <%= area_chart  Quake.group_by_day(:date).maximum(:siddet),width: "720px", height: "500px" ,colors: ["#a11342", "white"],label: "Buyukluk", xtitle: "Tarih",ytitle:"Buyukluk",legend: "bottom" %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<html>
  <head>
    <title>WatchersOfQuakes</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quakes/index.html.erb
<script src="http://www.jqueryscript.net/demo/Responsive-jQuery-News-Ticker-Plugin-with-Bootstrap-3-Bootstrap-News-Box/scripts/jquery.bootstrap.newsbox.min.js" type="text/javascript"></script>

<script>

    $(function () {
        $(".demo1").bootstrapNews({
            newsPerPage: 3,
            autoplay: true,
    		pauseOnHover:true,
            direction: 'up',
            newsTickerInterval: 4000,
            onToDo: function () {
                //console.log(this);
            }
        });

		$(".demo2").bootstrapNews({
            newsPerPage: 4,
            autoplay: true,
			pauseOnHover: true,
			navigation: false,
            direction: 'down',
            newsTickerInterval: 2500,
            onToDo: function () {
                //console.log(this);
            }
        });

        $("#demo3").bootstrapNews({
            newsPerPage: 3,
            autoplay: false,

            onToDo: function () {
                //console.log(this);
            }
        });
    });

</script>
<style>
body{
  background-color:rgb(68, 179, 234);
  background-repeat:no-repeat;
  background-size:cover;
}
.col-md-4{


   position: absolute;
   margin-top:11em;
   margin-left:32em;

   left: 0;
   right: 0;

}
h1{
  height: 43%;
      text-align:center;
      display:table;
      width:100%;

    }
#buttons{
  position: absolute;
  margin-left: 40em;
}
</style>
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-heading"> <span class="glyphicon"></span><b>SON DAKİKA DEPREMLER</b></div>
<div class="panel-body">
<div class="row">
<div class="col-xs-12">
<ul id="demo3" style="overflow-y: hidden; height: 210px;">
  <%id=0%>
  <%@x.each do |dep|%>
    <div id="dep_info">
      <h4 style="color:red"id="news-item"><%="#{id+1} NUMARALI DEPREM "%></h4>
      <h4 id ="news-item">Yer:<%=dep.place%></h4>
      <h4 id ="news-item">Tarih:<%=dep.date%></h4>
      <h4 id ="news-item">Büyüklük:<%=dep.siddet%></h4>
      <h4 id ="news-item">Şehir:<%=dep.city%></h4>
      <hr></hr>
    </div>
    <%id+=1%>
    <%if id==10%>
      <%break%>
    <%end%>

  <%end%>


</ul>
</div>
</div>
</div>
<div class="panel-footer"> <ul class="pagination pull-right" style="margin: 0px;"><li><a href="#" class="prev"><span class="glyphicon glyphicon-chevron-down"></span></a></li><li><a href="#" class="next"><span class="glyphicon glyphicon-chevron-up"></span></a></li></ul><div class="clearfix"></div></div>
</div>
</div>

<h1 style="font-size:60px;">TÜRKİYE DEPREMLERİ</h1>

<div id="buttons">
  <div class="btn-group">
    <%= link_to "ARAMA", searches_path, :class => "btn btn-default btn-lg btn-block btn-huge"%>
</div>
<div class="btn-group">
  <%= link_to "VERİ ANALİZİ", interactive_page_path, :class => "btn btn-default btn-lg btn-block btn-huge"%>
</div>
</div>

app/views/quakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @dep.date %>

app/views/searches/index.html.erb
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<STYLE>
@import url('https://fonts.googleapis.com/css?family=Bungee');

#search_info{
    background-color: rgb(244, 197, 66);
    font-family: 'Bungee', cursive;

}
.form-control input-md{
  color:red;
}
h1{
    text-align: left;
}
.btn3d.btn-white:active, .btn3d.btn-white.active {
    color: white;
    background-color:white;
    position: relative;
}
#submit_tag{
  text-align: left;
}
#submit:active{
}
.select_tag_city{
  width: 20em;
  margin-left: 0em;
}
#slider-6{
  width: 400px;
}
#search-form-pre{
    display: table;
    margin: 0 auto;
    background-color: rgb(32, 33, 35);
    margin-top: 10em;
    padding: 20px;
}
h1{
  color: black;
  font-size: 30px;
  font-weight: 400;
  font-style:normal;
  font-family: "Roboto", helvetica, arial, sans-serif;
  text-transform:uppercase;
}
#maximum_distance{
  background-color: rgb(32, 33, 35);
}

#minimum_distance{
  background-color: rgb(32, 33, 35);
}
.field{
  color:white;
}
body{
  background-color:rgb(68, 179, 234);
}
</STYLE>
<div id="search-form-pre">
  <h1 style="color:white;">QUAKES_SEARCH_SYSTEM</h1>

  <%= form_tag(shows_url, :method => "post", id: "search-form") do %>
<div class="select_tag_city">
    <%= select_tag :city_name,options_for_select(@cities,id:"radius"),:class=>"form-control input-md",:include_blank=>true%>
  </div>

    <p>


        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script>
        $(function() {
           $( "#slider-6" ).slider({
              range:true,
              min: 0,
              max: 1500,
              values: [ 0, 15000 ],
              start: function( event, ui ) {
                 $( "#maximum_distance" )
                    .val(ui.values[ 0 ] + ui.values[ 1 ] );
              },
              stop: function( event, ui ) {
                 $( "#minimum_distance" )
                    .val(ui.values[ 0 ] + ui.values[ 1 ] );
              },
              change: function( event, ui ) {
                 $( "#changevalue" )
                    .val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
              },
              slide: function( event, ui ) {
                 $( "#slidevalue" )
                    .val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
              }
          });
        });
        </script>
      </head>
      <body>

        <div id="slider-6"></div>
        <p>
           <label for="maximum_distance" style="color:white;"  id="label1">Maksimum Uzaklık:</label>
           <div class="field">
               <%=number_field_tag :maximum_distance,id:"maximum_distance"%>
           </div>

           <label for="minimum_distance"  style="color:white;" id="label2">Minimum  Uzaklık:</label>
           <div class="field">
               <%=number_field_tag :minimum_distance,id:"maximum_distance"%>
           </div>
           <style>
           @import url('https://fonts.googleapis.com/css?family=Bungee');
                #label1,#label2{
                  color: black;
                  font-size: 30px;
                  font-weight: 400;
                  font-style:normal;
                  font-family: "Roboto", helvetica, arial, sans-serif;
                  text-transform:uppercase;

                }
                #stopvalue{
                    border:0;
                    color:#b9cd6d;
                    font-weight:bold;

                }
                #maximum_distance{
                    border:0;
                     color:black;
                    font-weight:bold;
                    font-family: 'Bungee', cursive;
                    font-size: 30px;
                }
                #minimum_distance{
                    border:0; color:#0000;
                    font-weight:bold;
                    font-family: 'Bungee', cursive;

                    font-size: 30px;
                }

           </style>

        </p>




    <br>
  <div id="submit_tag">
    <%= submit_tag "Search",class:"btn3d btn btn-white btn-lg" ,id:"submit"%>
  </div>
  <% end %>
</div>